// <auto-generated />
using System;
using InfosecLearningSystem_Backend.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfosecLearningSystem_Backend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250301063551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.ContentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsLesson")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lesson");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_id");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("module_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_content_items");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_content_items_module_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_content_items_parent_id");

                    b.ToTable("content_items", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.ExternalLogin", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ProviderData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_data");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_user_id");

                    b.HasKey("UserId", "Provider")
                        .HasName("pk_external_logins");

                    b.HasIndex("ProviderUserId")
                        .HasDatabaseName("ix_external_logins_provider_user_id");

                    b.ToTable("external_logins", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.Lesson", b =>
                {
                    b.Property<int>("ContentItemId")
                        .HasColumnType("integer")
                        .HasColumnName("content_item_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Duration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("duration");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Xp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("xp");

                    b.HasKey("ContentItemId")
                        .HasName("pk_lessons");

                    b.HasIndex("TypeName")
                        .HasDatabaseName("ix_lessons_type_name");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.LessonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_lesson_types");

                    b.HasAlternateKey("Name")
                        .HasName("ak_lesson_types_name");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_lesson_types_name");

                    b.ToTable("lesson_types", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.LifecycleState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_lifecycle_states");

                    b.HasAlternateKey("Name")
                        .HasName("ak_lifecycle_states_name");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_lifecycle_states_name");

                    b.ToTable("lifecycle_states", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("duration");

                    b.Property<int?>("LifecycleStateId")
                        .HasColumnType("integer")
                        .HasColumnName("lifecycle_state_id");

                    b.Property<string>("LifecycleStateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lifecycle_state_name");

                    b.Property<int?>("ProgressStateId")
                        .HasColumnType("integer")
                        .HasColumnName("progress_state_id");

                    b.Property<string>("ProgressStateName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("progress_state_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Xp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("xp");

                    b.HasKey("Id")
                        .HasName("pk_modules");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_modules_category_id");

                    b.HasIndex("LifecycleStateId")
                        .HasDatabaseName("ix_modules_lifecycle_state_id");

                    b.HasIndex("LifecycleStateName")
                        .HasDatabaseName("ix_modules_lifecycle_state_name");

                    b.HasIndex("ProgressStateId")
                        .HasDatabaseName("ix_modules_progress_state_id");

                    b.HasIndex("ProgressStateName")
                        .HasDatabaseName("ix_modules_progress_state_name");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("ix_modules_title");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.ModuleTag", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("module_id");

                    b.Property<string>("TagName")
                        .HasColumnType("text")
                        .HasColumnName("tag_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ModuleId", "TagName")
                        .HasName("pk_module_tags");

                    b.HasIndex("TagName")
                        .HasDatabaseName("ix_module_tags_tag_name");

                    b.ToTable("module_tags", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasAlternateKey("Name")
                        .HasName("ak_permissions_name");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_name");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.ProgressState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_progress_states");

                    b.HasAlternateKey("Name")
                        .HasName("ak_progress_states_name");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_progress_states_name");

                    b.ToTable("progress_states", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasAlternateKey("Name")
                        .HasName("ak_roles_name");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.RolePermission", b =>
                {
                    b.Property<string>("RoleName")
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.Property<string>("PermissionName")
                        .HasColumnType("text")
                        .HasColumnName("permission_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("RoleName", "PermissionName")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionName")
                        .HasDatabaseName("ix_role_permissions_permission_name");

                    b.HasIndex("RoleName")
                        .HasDatabaseName("ix_role_permissions_role_name");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text")
                        .HasColumnName("default_value");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_system_configs");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_system_configs_name");

                    b.ToTable("system_configs", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasAlternateKey("Name")
                        .HasName("ak_tags_name");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("RequirePasswordReset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("require_password_reset");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("PermissionName")
                        .HasColumnType("text")
                        .HasColumnName("permission_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("UserId", "PermissionName")
                        .HasName("pk_user_permissions");

                    b.HasIndex("PermissionName")
                        .HasDatabaseName("ix_user_permissions_permission_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_permissions_user_id");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.UserPermissionView", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("user_permissions_view", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("text")
                        .HasColumnName("avatar_path");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<int>("Xp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("xp");

                    b.HasKey("UserId")
                        .HasName("pk_user_profiles");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_display_name");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleName")
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("UserId", "RoleName")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleName")
                        .HasDatabaseName("ix_user_roles_role_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.ContentItem", b =>
                {
                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.Module", "Module")
                        .WithMany("ContentItems")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_items_modules_module_id");

                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.ContentItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_content_items_content_items_parent_id");

                    b.Navigation("Module");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.ExternalLogin", b =>
                {
                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_logins_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.Lesson", b =>
                {
                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.ContentItem", "ContentItem")
                        .WithOne("Lesson")
                        .HasForeignKey("InfosecLearningSystem_Backend.Domain.Models.Lesson", "ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_content_items_content_item_id");

                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.LessonType", "Type")
                        .WithMany("Lessons")
                        .HasForeignKey("TypeName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_lesson_types_type_name");

                    b.Navigation("ContentItem");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.Module", b =>
                {
                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.Category", "Category")
                        .WithMany("Modules")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modules_categories_category_id");

                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.LifecycleState", null)
                        .WithMany("Modules")
                        .HasForeignKey("LifecycleStateId")
                        .HasConstraintName("fk_modules_lifecycle_states_lifecycle_state_id");

                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.LifecycleState", "LifecycleState")
                        .WithMany()
                        .HasForeignKey("LifecycleStateName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modules_lifecycle_states_lifecycle_state_name");

                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.ProgressState", null)
                        .WithMany("Modules")
                        .HasForeignKey("ProgressStateId")
                        .HasConstraintName("fk_modules_progress_states_progress_state_id");

                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.ProgressState", "ProgressState")
                        .WithMany()
                        .HasForeignKey("ProgressStateName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modules_progress_states_progress_state_name");

                    b.Navigation("Category");

                    b.Navigation("LifecycleState");

                    b.Navigation("ProgressState");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.ModuleTag", b =>
                {
                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.Module", "Module")
                        .WithMany("ModuleTags")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_module_tags_modules_module_id");

                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.Tag", "Tag")
                        .WithMany("ModuleTags")
                        .HasForeignKey("TagName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_module_tags_tags_tag_name");

                    b.Navigation("Module");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.RolePermission", b =>
                {
                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_name");

                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_name");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.UserPermission", b =>
                {
                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_permissions_permission_name");

                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_permissions_users_user_id");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.UserProfile", b =>
                {
                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("InfosecLearningSystem_Backend.Domain.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.UserRole", b =>
                {
                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_name");

                    b.HasOne("InfosecLearningSystem_Backend.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.Category", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.ContentItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.LessonType", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.LifecycleState", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.Module", b =>
                {
                    b.Navigation("ContentItems");

                    b.Navigation("ModuleTags");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.ProgressState", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("InfosecLearningSystem_Backend.Domain.Models.Tag", b =>
                {
                    b.Navigation("ModuleTags");
                });
#pragma warning restore 612, 618
        }
    }
}
